version: "3.8"
services:
  app:
    build: .
    env_file: env/.env
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    env_file: env/.env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  db_data:
